spring:
  application:
   name: ms-discovery
  config:
    import: "classpath:application-vault.yml,vault://"

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
        defaultZone: ${eureka-server}
  instance:
    prefer-ip-address: true